export enum EAddressOwnershipType {
    OWNER = 'OWNER',
    MORTGAGE = 'MORTGAGE',
    RENTING = 'RENTING',
    BOARDING = 'BOARDING',
    LIVING_WITH_RELATIVES = 'LIVING_WITH_RELATIVES',
    OTHER = 'OTHER',
}
