export enum EAssetSaleType {
    PRIVATE = 'PRIVATE',
    DEALERSHIP = 'DEALERSHIP',
    ASSET_OWNER = 'ASSET_OWNER',
    BALLOON_REFINANCE = 'BALLOON_REFINANCE',
    MID_TERM_FINANCE = 'MID_TERM_FINANCE',
}
