export enum EMatchingEngineCreditHistory {
    FIRST_TIME = 'FIRST_TIME',
    CLEAR_CREDIT = 'CLEAR_CREDIT',
    PAID_DEFAULTS = 'PAID_DEFAULTS',
    UNPAID_DEFAULTS = 'UNPAID_DEFAULTS',
    PREV_COMP_CREDIT = 'PREV_COMP_CREDIT',
    EX_BANKRUPT = 'EX_BANKRUPT',
    BANKRUPT = 'BANKRUPT',
}

export enum ECreditHistory {
    FIRST_TIME = 'FIRST_TIME',
    CLEAR_CREDIT = 'CLEAR_CREDIT',
    PAID_DEFAULTS = 'PAID_DEFAULTS',
    UNPAID_DEFAULTS = 'UNPAID_DEFAULTS',
    PREVIOUS_COMPARABLE_CREDIT = 'PREVIOUS_COMPARABLE_CREDIT',
    EX_BANKRUPT = 'EX_BANKRUPT',
    BANKRUPT = 'BANKRUPT',
}
