export enum EMatchingEngineFinanceType {
    CONSUMER = 'CONSUMER',
    COMMERCIAL_LOW_DOC = 'COMMERCIAL_LOW_DOC',
    COMMERCIAL_FULL_DOC = 'COMMERCIAL_FULL_DOC',
    COMMERCIAL_ALT_DOC = 'COMMERCIAL_ALT_DOC',
    COMMERCIAL_LOW_DOC_LEASE = 'COMMERCIAL_LEASE',
    COMMERCIAL_FULL_DOC_LEASE = 'COMMERCIAL_LEASE_FULL_DOC',
    COMMERCIAL_ALT_DOC_LEASE = 'COMMERCIAL_LEASE_ALT_DOC',
}
export enum EFinanceType {
    CONSUMER = 'CONSUMER',
    COMMERCIAL_LOW_DOC = 'COMMERCIAL_LOW_DOC',
    COMMERCIAL_FULL_DOC = 'COMMERCIAL_FULL_DOC',
    COMMERCIAL_ALT_DOC = 'COMMERCIAL_ALT_DOC',
    COMMERCIAL_LEASE_LOW_DOC = 'COMMERCIAL_LEASE_LOW_DOC',
    COMMERCIAL_LEASE_FULL_DOC = 'COMMERCIAL_LEASE_FULL_DOC',
    COMMERCIAL_LEASE_ALT_DOC = 'COMMERCIAL_LEASE_ALT_DOC',
}
