export enum ECreditHistory {
    PAID_DEFAULTS = 'PAID_DEFAULTS',
    UNPAID_DEFAULTS = 'UNPAID_DEFAULTS',
    EX_BANKRUPT = 'EX_BANKRUPT',
    FIRST_TIME_LEND = 'FIRST_TIME_LEND',
    CLEAR_CREDIT_HISTORY = 'CLEAR_CREDIT_HISTORY',
    PREVIOUS_COMPARABLE_CREDIT = 'PREVIOUS_COMPARABLE_CREDIT',
    BANKRUPT = 'BANKRUPT',
}
