export enum ECriteriaType {
    IN_RANGE = 'IN_RANGE',
    ABOVE_MIN = 'ABOVE_MIN',
    BELOW_MAX = 'BELOW_MAX',
    ACCEPTED_OPTIONS = 'ACCEPTED_OPTIONS',
    OPTION_DEPENDENT_MAX = 'OPTION_DEPENDENT_MAX',
}
