export enum ELivingStatus {
    PROPERTY_OWNER = 'PROPERTY_OWNER',
    RENTING = 'RENTING',
    BOARDING = 'BOARDING',
    LIVING_WITH_RELATIVES = 'LIVING_WITH_RELATIVES',
    OWNER_MORTGAGE = 'OWNER_MORTGAGE',
    PROPERTY_OWNER_SPOUSE_NAME = 'PROPERTY_OWNER_SPOUSE_NAME',
}
