export enum EResidencyStatus {
    AUSTRALIAN_CITIZEN = 'AUSTRALIAN_CITIZEN',
    PERMANENT_RESIDENT = 'PERMANENT_RESIDENT',
    WORKING_SKILLS_SHORTAGE_VISA = 'WORKING_SKILLS_SHORTAGE_VISA',
    OTHER_VISA = 'OTHER_VISA',
    NON_RESIDENT = 'NON_RESIDENT',
}
