export enum ESaleType {
    PRIVATE = 'PRIVATE',
    DEALER = 'DEALER',
    SALE_AND_BUY_BACK = 'SALE_AND_BUY_BACK',
    BALLOON_REFINANCE = 'BALLOON_REFINANCE',
    MID_TERM_REFINANCE = 'MID_TERM_REFINANCE',
}
